Repository GabrielNSD/Simpatibot, pull requests merged in 2022-10, with the labels that each got.

#4 update readme with todolist
  README.md
Labels: documentation, enhancement

#5 Remover arquivo teste não utilizado
  teste.py
Labels: hacktoberfest-accepted

#6 Request automático de token do spotify
  .vscode/settings.json
  Functions/__pycache__/auth.cpython-38.pyc
  Functions/__pycache__/aux_functions.cpython-38.pyc
  Functions/auth.py
  Functions/aux_functions.py
Labels: hacktoberfest-accepted

#7 pull request template added
  .github/PULL_REQUEST_TEMPLATE
  .gitignore
Labels: documentation, hacktoberfest-accepted
